apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: gcp-pubsub-binding
spec:
  instanceRef:
    name: gcp-pubsub-instance
  secretName: gcp-pubsub-credentials
  parameters:
    # The user should update the service account here to point to the service
    # account in their project they created for this demo.
    # roles: ["roles/pubsub.admin"] <- commented out intentionally
    serviceAccount: sa-sb-b58f266e-8da4-4035-9a6b@primeval-legacy-180316.iam.gserviceaccount.com
    bindingType: publisher
